-- AlterTable
ALTER TABLE `Booking`
  ADD COLUMN `perNightPrice` DECIMAL(10, 2) NULL,
  ADD COLUMN `agentName` VARCHAR(100) NULL,
  ADD COLUMN `gstDays` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `numberOfAdults` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `numberOfChildren` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `gstMode` VARCHAR(20) NOT NULL DEFAULT 'NONE',
  ADD COLUMN `gstOnBasePrice` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `gstOnExtraCharge` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `bookingSource` VARCHAR(50) NULL;
